<<<<<<< HEAD
#index:
#    path: /
#    controller: App\Controller\MainController::homepage
=======
index:
    path: /
    controller: App\Controller\MainController::homepage
>>>>>>> Fixed project structure according good practice and added comments to parts of code
